package ovh.delalande.gaetan.shared.Util;

import android.hardware.Sensor;

public enum SensorsByType {

    /** Sensor name by type **/
     ACCELEROMETER (Sensor.TYPE_ACCELEROMETER, "ACCELEROMETER", "m/s2"),

     ACCELEROMETER_UNCALIBRATED (Sensor.TYPE_ACCELEROMETER_UNCALIBRATED, "ACCELEROMETER UNCALIBRATED", "m/s2"),

     AMBIENT_TEMPERATURE (Sensor.TYPE_AMBIENT_TEMPERATURE, "AMBIENT TEMPERATURE", "°C"),

     GAME_ROTATION_VECTOR (Sensor.TYPE_GAME_ROTATION_VECTOR, "GAME ROTATION VECTOR"),

     GEOMAGNETIC_ROTATION_VECTOR (Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR, "GEOMAGNETIC ROTATION VECTOR"),

     GRAVITY (Sensor.TYPE_GRAVITY , "GRAVITY", "m/s2"),

     GYROSCOPE (Sensor.TYPE_GYROSCOPE , "GYROSCOPE", "rad/s"),

     GYROSCOPE_UNCALIBRATED (Sensor.TYPE_GYROSCOPE_UNCALIBRATED , "GYROSCOPE UNCALIBRATED", "rad/s"),

     HEART_BEAT (Sensor.TYPE_HEART_BEAT , "HEART BEAT"),

     HEART_RATE (Sensor.TYPE_HEART_RATE , "HEART RATE"),

     LIGHT (Sensor.TYPE_LIGHT , "LIGHT", "lx"),

     LINEAR_ACCELERATION (Sensor.TYPE_LINEAR_ACCELERATION , "LINEAR ACCELERATION", "m/s2"),

     LOW_LATENCY_OFFBODY_DETECT (Sensor.TYPE_LOW_LATENCY_OFFBODY_DETECT , "LOW LATENCY OFFBODY DETECT"),

     MAGNETIC_FIELD (Sensor.TYPE_MAGNETIC_FIELD , "MAGNETIC FIELD", "μT"),

     MAGNETIC_FIELD_UNCALIBRATED (Sensor.TYPE_MAGNETIC_FIELD_UNCALIBRATED , "MAGNETIC FIELD UNCALIBRATED", "μT"),

     MOTION_DETECT (Sensor.TYPE_MOTION_DETECT , "MOTION DETECT"),

     TYPE_PRESSURE (Sensor.TYPE_PRESSURE , "TYPE_PRESSURE", "hPa"),

     PROXIMITY (Sensor.TYPE_PROXIMITY , "PROXIMITY"),

     RELATIVE_HUMIDITY (Sensor.TYPE_RELATIVE_HUMIDITY , "RELATIVE HUMIDITY", "%"),

     ROTATION_VECTOR (Sensor.TYPE_ROTATION_VECTOR , "ROTATION VECTOR"),

     SIGNIFICANT_MOTION (Sensor.TYPE_SIGNIFICANT_MOTION , "SIGNIFICANT MOTION"),

     STATIONARY_DETECT (Sensor.TYPE_STATIONARY_DETECT , "STATIONARY DETECT"),

     STEP_COUNTER (Sensor.TYPE_STEP_COUNTER , "STEP COUNTER", "step"),

     STEP_DETECTOR (Sensor.TYPE_STEP_DETECTOR , "STEP DETECTOR");


     public int type;
     public String name;
     public String unit;

     SensorsByType(int type, String name){
         this.type = type;
         this.name = name;
     }

     SensorsByType(int type, String name, String unit){
         this(type, name);
         this.unit = unit;
     }

}
